export const menu = [
    {
        id: 1,
        title: "Boso-Lagman",
        category: "main",
        price: 15.99,
        img: "https://faiza.kg/media/menu/dishes/IMG_4288.jpg",
        desc: `Laghman is a popular dish of Central Asian cuisine. It is prepared from stretched noodles, meat and vegetables. Noodles are stretched by hands. To add a flavor, spices and herbs are added. The dish is served hot. «Boso» - is a kind of laghman that is fried on the pan `,
    },
    {
        id: 2,
        title: "Manty",
        category: "main",
        price: 13.99,
        img: "https://faiza.kg/media/menu/dishes/8D762D3A-48B0-4574-B311-02F36438230F.jpeg",
        desc: `Manty is a traditional meat dish of Central Asian people. Manty are prepared from finely chopped meat and onions in thin dough. The dish is cooked on steam. `,
    },
    {
        id: 3,
        title: "Plov",
        category: "main",
        price: 6.99,
        img: "https://faiza.kg/media/menu/dishes/IMG_4309.jpg",
        desc: `Plov is made on the basis of rice "Laser" - a dish of rice and meat, which are cooked at the same time. Rice and its taste are of great importance in the preparation of pilaf. Each grain must be separated from the others. Chickpeas are added for a pleasant aroma.`,
    },
    {
        id: 4,
        title: "Kymyz",
        category: "drinks",
        price: 20.99,
        img: "https://faiza.kg/media/menu/dishes/kefir.jpg",
        desc: `The fermented milk drink, which is obtained from cow’s milk by fermentation. Kymyz a common drink in many nations of the world. It is a very useful product for the body, because it contains a large number of nutrients. It goes well with many dishes. `,
    },
    {
        id: 5,
        title: "Pelmeni",
        category: "soups",
        price: 22.99,
        img: "https://faiza.kg/media/menu/dishes/IMG_4339.jpg",
        desc: `A common dish made from dough stuffed with minced meat. Also, in addition to the meat, add the onion and spices. As an offer to try the cream sauce, dumplings which gives a nice creamy flavor and a delicate flavor.`,
    },
    {
        id: 6,
        title: "Compote",
        category: "drinks",
        price: 18.99,
        img: "https://faiza.kg/media/menu/dishes/IMG_4436.jpg",
        desc: `Compote – dessert drink made from a mixture of fruits and berries through their cooking. Good thirst quencher and is an excellent addition to the feast.`,
    },
    {
        id: 7,
        title: "Lamb Shashlyk",
        category: "shashlyk",
        price: 8.99,
        img: "https://faiza.kg/media/menu/dishes/DSC_0751.jpg",
        desc: `Central Asian and Eastern cuisines, which is rooted in the very old days. It is made from quality fresh lamb, marinated beforehand. Roasted over charcoal and served with fresh chopped onions.`,
    },
    {
        id: 8,
        title: "Liver shashlik",
        category: "shashlyk",
        price: 12.99,
        img: "https://faiza.kg/media/menu/dishes/DSC_0751.jpg",
        desc: `Eastern and Central Asian cuisine, which is rooted in the very old days. This type of kebab made from the liver and can be pleasant to diversify the usual menu. Cooked very quickly and also the liver has many useful properties. `,
    },
    {
        id: 9,
        title: "Pancakes with sour cream",
        category: "desserts",
        price: 16.99,
        img: "https://faiza.kg/media/menu/dishes/IMG_4225.jpg",
        desc: `Pancakes – a roasted culinary product made of very thin dough which is poured into a hot frying pan. Pancakes are served with a variety of snacks. In this embodiment, pancakes are served with a sour cream.`,
    },
    {
        id: 10,
        title: "Pancakes with cottage cheese",
        category: "desserts",
        price: 39.99,
        img: "https://faiza.kg/media/menu/dishes/IMG_4231.jpg",
        desc: `Pancakes – a roasted culinary product made of very thin dough which is poured into a hot frying pan. Pancakes are served with a variety of snacks. In this embodiment, pancakes are served with a fresh cottage cheese that makes the dish very nourishing.`,
    },
];